/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedMiMarcaRouteImport } from './routes/_authenticated/mi-marca'
import { Route as AuthenticatedGeneradorRouteImport } from './routes/_authenticated/generador'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMiMarcaRoute = AuthenticatedMiMarcaRouteImport.update({
  id: '/mi-marca',
  path: '/mi-marca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGeneradorRoute = AuthenticatedGeneradorRouteImport.update({
  id: '/generador',
  path: '/generador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generador': typeof AuthenticatedGeneradorRoute
  '/mi-marca': typeof AuthenticatedMiMarcaRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generador': typeof AuthenticatedGeneradorRoute
  '/mi-marca': typeof AuthenticatedMiMarcaRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/generador': typeof AuthenticatedGeneradorRoute
  '/_authenticated/mi-marca': typeof AuthenticatedMiMarcaRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/generador' | '/mi-marca' | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/generador' | '/mi-marca' | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/generador'
    | '/_authenticated/mi-marca'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mi-marca': {
      id: '/_authenticated/mi-marca'
      path: '/mi-marca'
      fullPath: '/mi-marca'
      preLoaderRoute: typeof AuthenticatedMiMarcaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generador': {
      id: '/_authenticated/generador'
      path: '/generador'
      fullPath: '/generador'
      preLoaderRoute: typeof AuthenticatedGeneradorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGeneradorRoute: typeof AuthenticatedGeneradorRoute
  AuthenticatedMiMarcaRoute: typeof AuthenticatedMiMarcaRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGeneradorRoute: AuthenticatedGeneradorRoute,
  AuthenticatedMiMarcaRoute: AuthenticatedMiMarcaRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
